name: $(date:yyyyMMdd)$(rev:.rr)

trigger:
  - master

stages:
  - stage: compile
    jobs:
      - job: aspnet_build
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: dotnet build 3_devops/Devops.sln
  - stage: test
    jobs:
      - job: aspnet_test
        pool:
          vmImage: ubuntu-18.04
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: test
              projects: 3_devops/Devops.sln
              arguments: --collect:"XPlat Code Coverage"
          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: cobertura
              summaryFileLocation: '**/TestResults/coverage.cobertura.xml'
  # - stage: analyze
  #   jobs:
  #     - job:
  #       pool:
  #         vmImage: ubuntu-18.04
  #       steps:
  #         - script: dotnet install --global dotnet-sonarscanner
  #         - script: |
  #             sonarscanner begin /k:devops-benjaminclegg /d:sonar-login=$(SONAR_LOGIN)
  #             dontnet build
  #             dotnet test
  #             sonarscanner end /d:sonar-login=$(SONAR_LOGIN)
  # - stage: pack
  #   jobs:
  #     - job:
  #       pool:
  #         vmImage: ubuntu-18.04
  #       steps:
  #         - script: docker image build -f 3_devops/dockerfile -t benjaminclegg/devops:$(BUILD_NAME)
  #         - script: docker login --username $(DOCKER_USER) --password $(DOCKER_TOKEN)
  #         - script: docker image push benjaminclegg/devops:$(BUILD_NAME)